# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IndexesIndexes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, info: str=None, version: str=None):  # noqa: E501
        """IndexesIndexes - a model defined in Swagger

        :param id: The id of this IndexesIndexes.  # noqa: E501
        :type id: str
        :param name: The name of this IndexesIndexes.  # noqa: E501
        :type name: str
        :param info: The info of this IndexesIndexes.  # noqa: E501
        :type info: str
        :param version: The version of this IndexesIndexes.  # noqa: E501
        :type version: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'info': str,
            'version': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'info': 'info',
            'version': 'version'
        }
        self._id = id
        self._name = name
        self._info = info
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'IndexesIndexes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The indexes_indexes of this IndexesIndexes.  # noqa: E501
        :rtype: IndexesIndexes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this IndexesIndexes.

        Unique identifier for this index type  # noqa: E501

        :return: The id of this IndexesIndexes.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this IndexesIndexes.

        Unique identifier for this index type  # noqa: E501

        :param id: The id of this IndexesIndexes.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this IndexesIndexes.

        Display name for this index type  # noqa: E501

        :return: The name of this IndexesIndexes.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this IndexesIndexes.

        Display name for this index type  # noqa: E501

        :param name: The name of this IndexesIndexes.
        :type name: str
        """

        self._name = name

    @property
    def info(self) -> str:
        """Gets the info of this IndexesIndexes.

        Documentation about this particular index type  # noqa: E501

        :return: The info of this IndexesIndexes.
        :rtype: str
        """
        return self._info

    @info.setter
    def info(self, info: str):
        """Sets the info of this IndexesIndexes.

        Documentation about this particular index type  # noqa: E501

        :param info: The info of this IndexesIndexes.
        :type info: str
        """

        self._info = info

    @property
    def version(self) -> str:
        """Gets the version of this IndexesIndexes.

        Version identifier for this endpoint, preferably in semantic versioning style  # noqa: E501

        :return: The version of this IndexesIndexes.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this IndexesIndexes.

        Version identifier for this endpoint, preferably in semantic versioning style  # noqa: E501

        :param version: The version of this IndexesIndexes.
        :type version: str
        """

        self._version = version
